int: -1
double: 6.66
string: "cat"
string_list: ["Carpe", "Diem"]
double_list: [1, 2, 4, 4, 2, 1]
namespace:
  int: -1
  double: 6.66
  string: "cat"
  string_list: ["Carpe", "Diem"]
  double_list: [1, 2, 4, 4, 2, 1]
matrix_3x3: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
